

export enum InvoiceLineType {
    PRODUCT = 'PRODUCT',
    CHARGES = 'CHARGES',
    SERVICES = 'SERVICES',
    TRANSPORT = 'TRANSPORT',
    SHIPPING = 'SHIPPING',
    DISCOUNT = 'DISCOUNT',
    TAX = 'TAX',
    LABOUR = 'LABOUR',
    PACKING = 'PACKING',
    HANDLING = 'HANDLING',
    FUEL_SURCHARGE = 'FUEL_SURCHARGE',
    CUSTOME_DUTY = 'CUSTOME_DUTY',
    INSURANCE = 'INSURANCE',
    STORAGE_FEES = 'STORAGE_FEES',
    ADMINISTRATIVE_FEES = 'ADMINISTRATIVE_FEES',
    EXPRESS_DELIEVERY = 'EXPRESS_DELIEVERY',
    INSTALLATION_FEES = 'INSTALLATION_FEES',
    LATE_PAYMENT_FEES = 'LATE_PAYMENT_FEES',
    CLEANING_FEES = 'CLEANING_FEES',
    MISCELLANEOUS = 'MISCELLANEOUS',


    // or more categories as needed
  }
  