export const PERMISSIONS = {
  USERS: {
    CREATE: 'users.create',
    READ: 'users.read',
    UPDATE: 'users.update',
    DELETE: 'users.delete',
  },
  ROLES: {
    CREATE: 'roles.create',
    READ: 'roles.read',
    UPDATE: 'roles.update',
    DELETE: 'roles.delete',
  },
  COMPANIES: {
    CREATE: 'companies.create',
    READ: 'companies.read',
    UPDATE: 'companies.update',
    DELETE: 'companies.delete',
  },
  COMPANY_OWNERS: {
    CREATE: 'companyOwners.create',
    READ: 'companyOwners.read',
    UPDATE: 'companyOwners.update',
    DELETE: 'companyOwners.delete',
  },
  PARTNERS: {
    CREATE: 'partners.create',
    READ: 'partners.read',
    UPDATE: 'partners.update',
    DELETE: 'partners.delete',
  },
  EMPLOYEES: {
    CREATE: 'employees.create',
    READ: 'employees.read',
    UPDATE: 'employees.update',
    DELETE: 'employees.delete',
  },
  UOM: {
    CREATE: 'uom.create',
    READ: 'uom.read',
    UPDATE: 'uom.update',
    DELETE: 'uom.delete',
  },
  ACCOUNTS: {
    CREATE: 'accounts.create',
    READ: 'accounts.read',
    UPDATE: 'accounts.update',
    DELETE: 'accounts.delete',
  },
  CURRENCIES: {
    CREATE: 'currencies.create',
    READ: 'currencies.read',
    UPDATE: 'currencies.update',
    DELETE: 'currencies.delete',
  },
  EXCHANGE_RATES: {
    CREATE: 'exchangeRates.create',
    READ: 'exchangeRates.read',
    UPDATE: 'exchangeRates.update',
    DELETE: 'exchangeRates.delete',
  },
  JOURNAL: {
    CREATE: 'journal.create',
    READ: 'journal.read',
    UPDATE: 'journal.update',
    DELETE: 'journal.delete',
  },
  PRICE_LISTS: {
    CREATE: 'priceLists.create',
    READ: 'priceLists.read',
    UPDATE: 'priceLists.update',
    DELETE: 'priceLists.delete',
  },
  SUPPLIERS: {
    CREATE: 'suppliers.create',
    READ: 'suppliers.read',
    UPDATE: 'suppliers.update',
    DELETE: 'suppliers.delete',
  },
  CUSTOMERS: {
    CREATE: 'customers.create',
    READ: 'customers.read',
    UPDATE: 'customers.update',
    DELETE: 'customers.delete',
  },
  TRADERS: {
    CREATE: 'traders.create',
    READ: 'traders.read',
    UPDATE: 'traders.update',
    DELETE: 'traders.delete',
  },
  BROKERS: {
    CREATE: 'brokers.create',
    READ: 'brokers.read',
    UPDATE: 'brokers.update',
    DELETE: 'brokers.delete',
  },
  BROKERAGE_AGREEMENTS: {
    CREATE: 'brokerageAgreements.create',
    READ: 'brokerageAgreements.read',
    UPDATE: 'brokerageAgreements.update',
    DELETE: 'brokerageAgreements.delete',
  },
  BROKERAGE_TRANSACTIONS: {
    CREATE: 'brokerageTransactions.create',
    READ: 'brokerageTransactions.read',
    UPDATE: 'brokerageTransactions.update',
    DELETE: 'brokerageTransactions.delete',
  },
  CONTACTS: {
    CREATE: 'contacts.create',
    READ: 'contacts.read',
    UPDATE: 'contacts.update',
    DELETE: 'contacts.delete',
  },
  INVENTORY: {
    CREATE: 'inventory.create',
    READ: 'inventory.read',
    UPDATE: 'inventory.update',
    DELETE: 'inventory.delete',
  },
  INVENTORY_MOVEMENTS: {
    CREATE: 'inventoryMovements.create',
    READ: 'inventoryMovements.read',
    UPDATE: 'inventoryMovements.update',
    DELETE: 'inventoryMovements.delete',
  },
  LOT_RAW_MATERIALS: {
    CREATE: 'lotRawMaterials.create',
    READ: 'lotRawMaterials.read',
    UPDATE: 'lotRawMaterials.update',
    DELETE: 'lotRawMaterials.delete',
  },
  LOTS: {
    CREATE: 'lots.create',
    READ: 'lots.read',
    UPDATE: 'lots.update',
    DELETE: 'lots.delete',
    LINK_PURCHASE_ORDER: 'lots.linkPurchaseOrder',
    LINK_SALES_ORDER: 'lots.linkSalesOrder',
    LINK_PRODUCTION_ORDER: 'lots.linkProductionOrder',
    LINK_INVOICE: 'lots.linkInvoice',
  },
  PACKAGING_ORDERS: {
    CREATE: 'packagingOrders.create',
    READ: 'packagingOrders.read',
    UPDATE: 'packagingOrders.update',
    DELETE: 'packagingOrders.delete',
  },
  PRICE_LIST_ITEMS: {
    CREATE: 'priceListItems.create',
    READ: 'priceListItems.read',
    UPDATE: 'priceListItems.update',
    DELETE: 'priceListItems.delete',
  },
  PROCESSING_STAGES: {
    CREATE: 'processingStages.create',
    READ: 'processingStages.read',
    UPDATE: 'processingStages.update',
    DELETE: 'processingStages.delete',
  },
  PRODUCT_CATEGORIES: {
    CREATE: 'productCategories.create',
    READ: 'productCategories.read',
    UPDATE: 'productCategories.update',
    DELETE: 'productCategories.delete',
  },
  PRODUCTION_ORDER_STAGES: {
    CREATE: 'productionOrderStages.create',
    READ: 'productionOrderStages.read',
    UPDATE: 'productionOrderStages.update',
    DELETE: 'productionOrderStages.delete',
  },
  PRODUCTION_ORDERS: {
    CREATE: 'productionOrders.create',
    READ: 'productionOrders.read',
    UPDATE: 'productionOrders.update',
    DELETE: 'productionOrders.delete',
  },
  PRODUCTS: {
    CREATE: 'products.create',
    READ: 'products.read',
    UPDATE: 'products.update',
    DELETE: 'products.delete',
  },
  WAREHOUSES: {
    CREATE: 'warehouses.create',
    READ: 'warehouses.read',
    UPDATE: 'warehouses.update',
    DELETE: 'warehouses.delete',
  },
  SALES_ORDERS: {
    CREATE: 'salesOrders.create',
    READ: 'salesOrders.read',
    UPDATE: 'salesOrders.update',
    DELETE: 'salesOrders.delete',
  },
  INVOICES: {
    CREATE: 'invoices.create',
    READ: 'invoices.read',
    UPDATE: 'invoices.update',
    DELETE: 'invoices.delete',
  },
  CREDIT_NOTES: {
    CREATE: 'creditNotes.create',
    READ: 'creditNotes.read',
    UPDATE: 'creditNotes.update',
    DELETE: 'creditNotes.delete',
  },
  DEBIT_NOTES: {
    CREATE: 'debitNotes.create',
    READ: 'debitNotes.read',
    UPDATE: 'debitNotes.update',
    DELETE: 'debitNotes.delete',
  },
  PAYMENTS: {
    CREATE: 'payments.create',
    READ: 'payments.read',
    UPDATE: 'payments.update',
    DELETE: 'payments.delete',
  },
  PAYMENT_METHODS: {
    CREATE: 'paymentMethods.create',
    READ: 'paymentMethods.read',
    UPDATE: 'paymentMethods.update',
    DELETE: 'paymentMethods.delete',
  },
  TRANSACTIONS_PAYMENTS: {
    CREATE: 'transactionsPayments.create',
    READ: 'transactionsPayments.read',
    UPDATE: 'transactionsPayments.update',
    DELETE: 'transactionsPayments.delete',
  },
  PURCHASE_ORDERS: {
    CREATE: 'purchaseOrders.create',
    READ: 'purchaseOrders.read',
    UPDATE: 'purchaseOrders.update',
    DELETE: 'purchaseOrders.delete',
    ADD_LINE: 'purchaseOrders.addLine',
    UPDATE_LINE: 'purchaseOrders.updateLine',
    DELETE_LINE: 'purchaseOrders.deleteLine',
    GET_LINE: 'purchaseOrders.getLine',
  },
  WEIGHBRIDGE_TICKETS: {
    CREATE: 'weighbridgeTickets.create',
    READ: 'weighbridgeTickets.read',
    UPDATE: 'weighbridgeTickets.update',
    DELETE: 'weighbridgeTickets.delete',
  },
  GRAIN_QUALITY_TESTS: {
    CREATE: 'grainQualityTests.create',
    READ: 'grainQualityTests.read',
    UPDATE: 'grainQualityTests.update',
    DELETE: 'grainQualityTests.delete',
  },
  AUDIT_TRAILS: {
    CREATE: 'auditTrails.create',
    READ: 'auditTrails.read',
    UPDATE: 'auditTrails.update',
    DELETE: 'auditTrails.delete',
  },
  WORKFLOWS: {
    CREATE: 'workflows.create',
    READ: 'workflows.read',
    UPDATE: 'workflows.update',
    DELETE: 'workflows.delete',
  },
  DAY_BOOK: {
    CREATE: 'daybook.create',
    READ: 'daybook.read',
    UPDATE: 'daybook.update',
    DELETE: 'daybook.delete',
  },
  CONTACT_LEDGER: {
    CREATE: 'contactLedger.create',
    READ: 'contactLedger.read',
    UPDATE: 'contactLedger.update',
    DELETE: 'contactLedger.delete',
  },
  REPORTS: {
    TRIAL_BALANCE: 'reports.trialBalance',
    BALANCE_SHEET: 'reports.balanceSheet',
    PROFIT_AND_LOSS: 'reports.profitAndLoss',
    CONTACT_LEDGER: 'reports.contactLedger',
    AGING: 'reports.aging',
    INCOME_STATEMENT: 'reports.incomeStatement',
  },
  PERMISSIONS: {
    CREATE: 'permissions.create',
    READ: 'permissions.read',
    UPDATE: 'permissions.update',
    DELETE: 'permissions.delete',
    ASSIGN: 'permissions.assign',
    UNASSIGN: 'permissions.unassign',
    ASSIGN_ALL: 'permissions.assignAll',
    REPLACE: 'permissions.replace',
  },
};
