export const PERMISSIONS = {
  USERS: {
    CREATE: 'users.create',
    READ: 'users.read',
    UPDATE: 'users.update',
    DELETE: 'users.delete',
  },
  ROLES: {
    CREATE: 'roles.create',
    READ: 'roles.read',
    UPDATE: 'roles.update',
    DELETE: 'roles.delete',
  },
  COMPANIES: {
    CREATE: 'companies.create',
    READ: 'companies.read',
    UPDATE: 'companies.update',
    DELETE: 'companies.delete',
  },
  COMPANY_OWNERS: {
    CREATE: 'company_owner.create',
    READ: 'company_owner.read',
    UPDATE: 'company_owner.update',
    DELETE: 'company_owner.delete',
  },
  PARTNERS: {
    CREATE: 'partners.create',
    READ: 'partners.read',
    UPDATE: 'partners.update',
    DELETE: 'partners.delete',
  },
  EMPLOYEES: {
    CREATE: 'employees.create',
    READ: 'employees.read',
    UPDATE: 'employees.update',
    DELETE: 'employees.delete',
  },
  UOM: {
    CREATE: 'uom.create',
    READ: 'uom.read',
    UPDATE: 'uom.update',
    DELETE: 'uom.delete',
  },
  ACCOUNTS: {
    CREATE: 'accounts.create',
    READ: 'accounts.read',
    UPDATE: 'accounts.update',
    DELETE: 'accounts.delete',
  },
  CURRENCIES: {
    CREATE: 'currencies.create',
    READ: 'currencies.read',
    UPDATE: 'currencies.update',
    DELETE: 'currencies.delete',
  },
  EXCHANGE_RATES: {
    CREATE: 'exchange_rates.create',
    READ: 'exchange_rates.read',
    UPDATE: 'exchange_rates.update',
    DELETE: 'exchange_rates.delete',
  },
  JOURNAL: {
    CREATE: 'journal.create',
    READ: 'journal.read',
    UPDATE: 'journal.update',
    DELETE: 'journal.delete',
  },
  PRICE_LISTS: {
    CREATE: 'price_lists.create',
    READ: 'price_lists.read',
    UPDATE: 'price_lists.update',
    DELETE: 'price_lists.delete',
  },
  SUPPLIERS: {
    CREATE: 'suppliers.create',
    READ: 'suppliers.read',
    UPDATE: 'suppliers.update',
    DELETE: 'suppliers.delete',
  },
  CUSTOMERS: {
    CREATE: 'customers.create',
    READ: 'customers.read',
    UPDATE: 'customers.update',
    DELETE: 'customers.delete',
  },
  TRADERS: {
    CREATE: 'traders.create',
    READ: 'traders.read',
    UPDATE: 'traders.update',
    DELETE: 'traders.delete',
  },
  BROKERS: {
    CREATE: 'brokers.create',
    READ: 'brokers.read',
    UPDATE: 'brokers.update',
    DELETE: 'brokers.delete',
  },
  BROKERAGE_AGREEMENTS: {
    CREATE: 'brokerage_agreements.create',
    READ: 'brokerage_agreements.read',
    UPDATE: 'brokerage_agreements.update',
    DELETE: 'brokerage_agreements.delete',
  },
  BROKERAGE_TRANSACTIONS: {
    CREATE: 'brokerage_transactions.create',
    READ: 'brokerage_transactions.read',
    UPDATE: 'brokerage_transactions.update',
    DELETE: 'brokerage_transactions.delete',
  },
  CONTACTS: {
    CREATE: 'contacts.create',
    READ: 'contacts.read',
    UPDATE: 'contacts.update',
    DELETE: 'contacts.delete',
  },
  INVENTORY: {
    CREATE: 'inventory.create',
    READ: 'inventory.read',
    UPDATE: 'inventory.update',
    DELETE: 'inventory.delete',
  },
  INVENTORY_MOVEMENTS: {
    CREATE: 'inventory_movements.create',
    READ: 'inventory_movements.read',
    UPDATE: 'inventory_movements.update',
    DELETE: 'inventory_movements.delete',
  },
  LOT_RAW_MATERIALS: {
    CREATE: 'lot_raw_materials.create',
    READ: 'lot_raw_materials.read',
    UPDATE: 'lot_raw_materials.update',
    DELETE: 'lot_raw_materials.delete',
  },
  LOTS: {
    CREATE: 'lots.create',
    READ: 'lots.read',
    UPDATE: 'lots.update',
    DELETE: 'lots.delete',
    LINK_PURCHASE_ORDER: 'lots.linkPurchaseOrder',
    LINK_SALES_ORDER: 'lots.linkSalesOrder',
    LINK_PRODUCTION_ORDER: 'lots.linkProductionOrder',
    LINK_INVOICE: 'lots.linkInvoice',
  },
  PACKAGING_ORDERS: {
    CREATE: 'packaging_orders.create',
    READ: 'packaging_orders.read',
    UPDATE: 'packaging_orders.update',
    DELETE: 'packaging_orders.delete',
  },
  PRICE_LIST_ITEMS: {
    CREATE: 'price_list_items.create',
    READ: 'price_list_items.read',
    UPDATE: 'price_list_items.update',
    DELETE: 'price_list_items.delete',
  },
  PROCESSING_STAGES: {
    CREATE: 'processing_stages.create',
    READ: 'processing_stages.read',
    UPDATE: 'processing_stages.update',
    DELETE: 'processing_stages.delete',
  },
  PRODUCT_CATEGORIES: {
    CREATE: 'product_categories.create',
    READ: 'product_categories.read',
    UPDATE: 'product_categories.update',
    DELETE: 'product_categories.delete',
  },
  PRODUCTION_ORDER_STAGES: {
    CREATE: 'production_order_stages.create',
    READ: 'production_order_stages.read',
    UPDATE: 'production_order_stages.update',
    DELETE: 'production_order_stages.delete',
  },
  PRODUCTION_ORDERS: {
    CREATE: 'production_orders.create',
    READ: 'production_orders.read',
    UPDATE: 'production_orders.update',
    DELETE: 'production_orders.delete',
  },
  PRODUCTS: {
    CREATE: 'products.create',
    READ: 'products.read',
    UPDATE: 'products.update',
    DELETE: 'products.delete',
  },
  WAREHOUSES: {
    CREATE: 'warehouses.create',
    READ: 'warehouses.read',
    UPDATE: 'warehouses.update',
    DELETE: 'warehouses.delete',
  },
  SALES_ORDERS: {
    CREATE: 'sales_orders.create',
    READ: 'sales_orders.read',
    UPDATE: 'sales_orders.update',
    DELETE: 'sales_orders.delete',
  },
  INVOICES: {
    CREATE: 'invoices.create',
    READ: 'invoices.read',
    UPDATE: 'invoices.update',
    DELETE: 'invoices.delete',
  },
  CREDIT_NOTES: {
    CREATE: 'credit_notes.create',
    READ: 'credit_notes.read',
    UPDATE: 'credit_notes.update',
    DELETE: 'credit_notes.delete',
  },
  DEBIT_NOTES: {
    CREATE: 'debit_notes.create',
    READ: 'debit_notes.read',
    UPDATE: 'debit_notes.update',
    DELETE: 'debit_notes.delete',
  },
  PAYMENTS: {
    CREATE: 'payments.create',
    READ: 'payments.read',
    UPDATE: 'payments.update',
    DELETE: 'payments.delete',
  },
  PAYMENT_METHODS: {
    CREATE: 'payment_methods.create',
    READ: 'payment_methods.read',
    UPDATE: 'payment_methods.update',
    DELETE: 'payment_methods.delete',
  },
  TRANSACTIONS_PAYMENTS: {
    CREATE: 'transactions_payments.create',
    READ: 'transactions_payments.read',
    UPDATE: 'transactions_payments.update',
    DELETE: 'transactions_payments.delete',
  },
  PURCHASE_ORDERS: {
    CREATE: 'purchase_orders.create',
    READ: 'purchase_orders.read',
    UPDATE: 'purchase_orders.update',
    DELETE: 'purchase_orders.delete',
    ADD_LINE: 'purchase_orders.addLine',
    UPDATE_LINE: 'purchase_orders.updateLine',
    DELETE_LINE: 'purchase_orders.deleteLine',
    GET_LINE: 'purchase_orders.getLine',
  },
  WEIGHBRIDGE_TICKETS: {
    CREATE: 'weighbridge_tickets.create',
    READ: 'weighbridge_tickets.read',
    UPDATE: 'weighbridge_tickets.update',
    DELETE: 'weighbridge_tickets.delete',
  },
  GRAIN_QUALITY_TESTS: {
    CREATE: 'grain_quality_tests.create',
    READ: 'grain_quality_tests.read',
    UPDATE: 'grain_quality_tests.update',
    DELETE: 'grain_quality_tests.delete',
  },
  AUDIT_TRAILS: {
    CREATE: 'audit_trails.create',
    READ: 'audit_trails.read',
    UPDATE: 'audit_trails.update',
    DELETE: 'audit_trails.delete',
  },
  WORKFLOWS: {
    CREATE: 'workflows.create',
    READ: 'workflows.read',
    UPDATE: 'workflows.update',
    DELETE: 'workflows.delete',
  },
  DAY_BOOK: {
    CREATE: 'day_book.create',
    READ: 'day_book.read',
    UPDATE: 'day_book.update',
    DELETE: 'day_book.delete',
  },
  CONTACT_LEDGER: {
    CREATE: 'contact_ledger.create',
    READ: 'contact_ledger.read',
    UPDATE: 'contact_ledger.update',
    DELETE: 'contact_ledger.delete',
  },
  REPORTS: {
    TRIAL_BALANCE: 'reports.trialBalance',
    BALANCE_SHEET: 'reports.balanceSheet',
    PROFIT_AND_LOSS: 'reports.profitAndLoss',
    CONTACT_LEDGER: 'reports.contactLedger',
    AGING: 'reports.aging',
    INCOME_STATEMENT: 'reports.incomeStatement',
  },
  PERMISSIONS: {
    CREATE: 'permissions.create',
    READ: 'permissions.read',
    UPDATE: 'permissions.update',
    DELETE: 'permissions.delete',
  },
};
